name: Entregables


on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4
with:
  commit_message: Entrega de la actividad 1