name: Entregables


on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4
      - name: Paso 2 - Setup python
        uses: actions/setup-python@v5
      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv
      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate
      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip
      - name: Paso 6 - Instalar dependecias
        run: pip install -e .
with:
  commit_message: Entrega de la actividad 1